# Generated by Django 4.0.4 on 2022-07-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
